/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteCreateDtoContent } from './noteCreateDtoContent';


export interface NoteCreateDto { 
    content: NoteCreateDtoContent;
    to: NoteCreateDtoContent;
    type: NoteCreateDto.TypeEnum;
}
export namespace NoteCreateDto {
    export type TypeEnum = 'Note';
    export const TypeEnum = {
        Note: 'Note' as TypeEnum
    };
}


