/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteCreateDtoName } from './noteCreateDtoName';
import { NoteCreateDtoContent } from './noteCreateDtoContent';


export interface ObjectDto { 
    id: string;
    type: string;
    attributedTo: string;
    content: NoteCreateDtoContent;
    context: string;
    name?: NoteCreateDtoName;
    published: string;
    to?: NoteCreateDtoName;
}

