/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ObjectDtoTo } from './objectDtoTo';


export interface ObjectDto { 
    id: string;
    content: string;
    context: string;
    published: string;
    to: ObjectDtoTo;
}

