/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonDto { 
    /**
     * The ID of the user
     */
    id: string;
    /**
     * The name of the user
     */
    name: string;
    summary: string;
    type: string;
    preferredUsername: string;
    following: string;
}

