/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NoteCreateDto } from './noteCreateDto';
import { NoteCreateDtoName } from './noteCreateDtoName';
import { NoteCreateDtoContent } from './noteCreateDtoContent';


/**
 * @type PostOutboxRequest
 * @export
 */
export type PostOutboxRequest = NoteCreateDto;

