/**
 * Yuforium
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActorDtoType } from './actorDtoType';
import { ActorDtoContext } from './actorDtoContext';


export interface ActorDto { 
    context: ActorDtoContext;
    type: ActorDtoType;
    /**
     * The name of the actor
     */
    name: string;
    /**
     * A descriptive summary of the actor
     */
    summary: string;
    /**
     * The preferred username of the actor, used in mentions and other places
     */
    preferredUsername: string;
    /**
     * The ID of the actor
     */
    id: string;
}

