export * from './app.service';
import { AppService } from './app.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './forum.service';
import { ForumService } from './forum.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AppService, AuthService, DefaultService, ForumService, UserService];
