// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    ForumCreateDto,
} from '../models';

export interface AppControllerPostOutboxRequest {
    forumCreateDto: ForumCreateDto;
}

/**
 * no description
 */
export class AppApi extends BaseAPI {

    /**
     */
    appControllerGetService(): Observable<void>
    appControllerGetService(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    appControllerGetService(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        return this.request<void>({
            url: '/',
            method: 'GET',
        }, opts?.responseOpts);
    };

    /**
     */
    appControllerPostOutbox({ forumCreateDto }: AppControllerPostOutboxRequest): Observable<void>
    appControllerPostOutbox({ forumCreateDto }: AppControllerPostOutboxRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    appControllerPostOutbox({ forumCreateDto }: AppControllerPostOutboxRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(forumCreateDto, 'forumCreateDto', 'appControllerPostOutbox');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/outbox',
            method: 'POST',
            headers,
            body: forumCreateDto,
        }, opts?.responseOpts);
    };

}
