// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, HttpHeaders, throwIfNullOrUndefined, OperationOpts, RawAjaxResponse } from '../runtime';
import {
    LoginDto,
} from '../models';

export interface LoginRequest {
    loginDto: LoginDto;
}

/**
 * no description
 */
export class AuthApi extends BaseAPI {

    /**
     */
    login({ loginDto }: LoginRequest): Observable<void>
    login({ loginDto }: LoginRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    login({ loginDto }: LoginRequest, opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        throwIfNullOrUndefined(loginDto, 'loginDto', 'login');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>({
            url: '/auth/login',
            method: 'POST',
            headers,
            body: loginDto,
        }, opts?.responseOpts);
    };

    /**
     */
    profile(): Observable<void>
    profile(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>>
    profile(opts?: OperationOpts): Observable<void | RawAjaxResponse<void>> {
        const headers: HttpHeaders = {
            ...(this.configuration.username != null && this.configuration.password != null ? { Authorization: `Basic ${btoa(this.configuration.username + ':' + this.configuration.password)}` } : undefined),
        };

        return this.request<void>({
            url: '/auth/profile',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
