// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ForumCreateDto
 */
export interface ForumCreateDto {
    /**
     * @type {string}
     * @memberof ForumCreateDto
     */
    id: string;
    /**
     * @type {string}
     * @memberof ForumCreateDto
     */
    name: string;
    /**
     * @type {string}
     * @memberof ForumCreateDto
     */
    summary: string;
}
