// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface NoteCreateDto
 */
export interface NoteCreateDto {
    /**
     * @type {string}
     * @memberof NoteCreateDto
     */
    content: string;
    /**
     * @type {string | Array<string>}
     * @memberof NoteCreateDto
     */
    to: string | Array<string> | null;
    /**
     * @type {string}
     * @memberof NoteCreateDto
     */
    type: NoteCreateDtoTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum NoteCreateDtoTypeEnum {
    Note = 'Note'
}

