// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface PersonDto
 */
export interface PersonDto {
    /**
     * The ID of the user
     * @type {string}
     * @memberof PersonDto
     */
    id: string;
    /**
     * @type {string}
     * @memberof PersonDto
     */
    summary: string;
    /**
     * @type {string}
     * @memberof PersonDto
     */
    type: string;
    /**
     * @type {string}
     * @memberof PersonDto
     */
    preferredUsername: string;
    /**
     * @type {string}
     * @memberof PersonDto
     */
    following: string;
}
