// tslint:disable
/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UserCreateDto
 */
export interface UserCreateDto {
    /**
     * @type {string}
     * @memberof UserCreateDto
     */
    username: string;
    /**
     * @type {string}
     * @memberof UserCreateDto
     */
    name?: string;
    /**
     * @type {string}
     * @memberof UserCreateDto
     */
    summary?: string;
    /**
     * @type {string}
     * @memberof UserCreateDto
     */
    password: string;
}
