/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NoteCreateDto { 
    content: string;
    to: string | Array<string>;
    type: NoteCreateDto.TypeEnum;
}
export namespace NoteCreateDto {
    export type TypeEnum = 'Note';
    export const TypeEnum = {
        Note: 'Note' as TypeEnum
    };
}