/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserContentQueryOptionsDto { 
    /**
     * Comma separated list of Activity Streams object types to include in the response.
     */
    type?: string;
    /**
     * The number of items to skip before returning the remaining items.
     */
    skip?: number;
    /**
     * The maximum number of items to return.
     */
    limit?: number;
}