/**
 * Yuforium API Specification
 * Yuforium API specification
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserCreateDto { 
    username: string;
    name?: string;
    summary?: string;
    password: string;
}