name: Build Docker Image
on:
  push:
    branches:
      - main
      - arm-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: true
          tags: yuforium/ui:latest, yuforium/ui:${{ github.sha }}
